language: elixir
elixir:
  - 1.5.2
  - 1.4.2
  - 1.2.6
otp_release:
  - 18.2.1
  - 19.1
cache:
  directories:
  - deps
  - /home/travis/download

before_install:
  - wget -P /home/travis/download/ -nc https://bitcoin.org/bin/bitcoin-core-0.14.0/bitcoin-0.14.0-x86_64-linux-gnu.tar.gz && tar -xzvf /home/travis/download/bitcoin-0.14.0-x86_64-linux-gnu.tar.gz -C /home/travis

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - /home/travis/bitcoin-0.14.0/bin/bitcoind -regtest -daemon
script:
  - sleep 15
  - mix test
  - mix coveralls.travis
notifications:
  recipients:
    - kelostrada@gmail.com
